name: Build Hasher

on:
#  push:
#    branches: [ main, master ]
#    tags: [ 'v*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        platform: [x64, x86]
        configuration: [Release]
        # platform: [x64, x86, AnyCPU]
        # configuration: [Release, Debug]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build Project
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" ${{ matrix.platform == 'x64' && 'x64' || 'x86' }}
          msbuild NppHash.csproj /m /p:Configuration="${{ matrix.configuration }}" /p:Platform="${{ matrix.platform }} /p:DevEnvDir="C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\Common7\IDE\""

      - name: Prepare Artifacts
        shell: pwsh
        run: |
          $dllPath = if ("${{ matrix.platform }}" -eq "AnyCPU") {
              "bin\${{ matrix.configuration }}\NppHasher.dll"
          } else {
              "bin\${{ matrix.platform }}\${{ matrix.configuration }}\NppHasher.dll"
          }

          $tagName = if ("${{ github.ref_type }}" -eq "tag") { "${{ github.ref_name }}" } else { "latest-build" }
          
          $archSuffix = if ("${{ matrix.platform }}" -eq "x64") { "x64" } else { "x86" }
          $archiveName = "NppHash_$($tagName)_$($archSuffix).7z"

          if (Test-Path $dllPath) {
              7z a -t7z -mx9 $archiveName $dllPath
              echo "ARCHIVE_NAME=$archiveName" >> $env:GITHUB_ENV
              echo "RELEASE_TAG=$tagName" >> $env:GITHUB_ENV
          } else {
              Write-Error "DLL not found at $dllPath"
              exit 1
          }

      - name: Upload to Workflow
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.platform }}-${{ matrix.configuration }}
          path: ${{ env.ARCHIVE_NAME }}
          retention-days: 1

  publish:
    needs: build
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: artifacts-*-Release
          merge-multiple: true

      - name: Set Release Tag
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "RELEASE_TAG=${{ github.ref_name }}" >> $GITHUB_ENV
          else
            echo "RELEASE_TAG=latest-build" >> $GITHUB_ENV
          fi

      - name: Delete Old Release (Auto-builds only)
        if: github.ref_type != 'tag'
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          delete_release: true
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          files: "*.7z"
          generate_release_notes: true
          prerelease: ${{ github.ref_type != 'tag' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
